# 以Deployment部署Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-k8s-cicd-test
spec:
  selector:
    matchLabels:
      app: springboot-demo-k8s-cicd-test
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-demo-k8s-cicd-test
    spec:
      containers:
        - name: springboot-demo-k8s-cicd-test
          image: registry.cn-hangzhou.aliyuncs.com/xiangwei-public/springboot-demo-k8s-cicd-test:1.1.0-RELEASE
          ports:
            - containerPort: 9090
---
# 创建Pod的Service
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-k8s-cicd-test
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: springboot-demo-k8s-cicd-test
---
# 创建Ingress，定义访问规则
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springboot-demo-k8s-cicd-test
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: springboot-demo-k8s-cicd-test
              servicePort: 9090